### ISSUE TITLE
Clamd connections are not being closed

### ISSUE THREAD

**Issue by jblackman** [dutchcoders/go-clamd#2]
I have encountered an issue in this otherwise excellent package, It appears that the connection to clamd is not being closed. I am running this on a Debian jessie system, with go v1.4.2. It's pretty easy to reproduce, just run the example from the README in a loop a thousand times, pause, and check the open files (e.g. using lsof).

``` go
package main

import (
    "bufio"
    "bytes"
    "fmt"
    clamd "github.com/dutchcoders/go-clamd"
    "os"
)

func main() {
    for i := 0; i < 1000; i++ {
        sendRequest("/var/run/clamav/clamd.ctl", clamd.EICAR)
    }
    fmt.Println("Hit <enter>")
    bufio.NewReader(os.Stdin).ReadString('\n')
}

func sendRequest(clamav string, content []byte) {
    c := clamd.NewClamd(clamav)

    reader := bytes.NewReader(content)
    response, err := c.ScanStream(reader)

    for s := range response {
        fmt.Printf("%v %v\n", s, err)
    }
}
```

Looking at the code, it appears that line clamd.go:282 is not firing:

``` go
wg.Wait()
```

On a whim, I changed the return value of conn.go:76 to return a pointer to the WaitGroup, on the hunch that the return value is being copied and so will never fire. This works.

``` go
func (c *CLAMDConn) readResponse() (chan string, *sync.WaitGroup, error) {
...
    return ch, &wg, nil

```

Do you agree with my diagnosis?

**Comment by kzsnow** [comment]
I just ran into the same issue with unclosed sockets. Your suggestion did fix it, thanks for the diagnosis.
